version: '3'

services:
  clickhouse-1:
    image: clickhouse/clickhouse-server:22.10
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      SHARD: shard1
      REPLICA: replica1
      KEEPER_ID: 1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    user: clickhouse
    volumes:
      - clickhouse1_data:/var/lib/clickhouse
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9440:9440'

  clickhouse-2:
    image: clickhouse/clickhouse-server:22.10
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      SHARD: shard1
      REPLICA: replica2
      KEEPER_ID: 2
    volumes:
      - clickhouse2_data:/var/lib/clickhouse
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '9001:9000'

  clickhouse-3:
    image: clickhouse/clickhouse-server:22.10
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      SHARD: shard2
      REPLICA: replica1
      KEEPER_ID: 3
    volumes:
      - clickhouse3_data:/var/lib/clickhouse
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '9002:9000'

  clickhouse-4:
    image: clickhouse/clickhouse-server:22.10
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      SHARD: shard2
      REPLICA: replica2
      KEEPER_ID: 4
    volumes:
      - clickhouse4_data:/var/lib/clickhouse
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '9003:9000'

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'

  uptrace:
    image: 'uptrace/uptrace:1.4.3'
    #image: 'uptrace/uptrace-dev:latest'
    restart: on-failure
    volumes:
      - ./uptrace.yml:/etc/uptrace/uptrace.yml
    #environment:
    #  - DEBUG=2
    ports:
      - '14317:14317'
      - '14318:14318'

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.70.0
    restart: on-failure
    user: '0:0' # required for logs
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - '4317:4317'
      - '4318:4318'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '8025:8025'

  vector:
    image: timberio/vector:0.28.X-alpine
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro

volumes:
  clickhouse1_data:
  clickhouse2_data:
  clickhouse3_data:
  clickhouse4_data:
  postgres_data:
